### ISSUE TITLE
Problems with line breaks

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/gptwrapper#230]
does not work, eg with the following prompt

```
consider the following code

print("1")
print("2")
print("3")
```

or with

```
apiVersion: v1
kind: Service
metadata:
  name: seedimage-svc
spec:
  type: ClusterIP
  selector:
    app: seedimage
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
```

--

The following screenshots should show the problem. When I send a prompt with line breaks (code), the line breaks disappear when the prompt is shown.

![image](https://github.com/user-attachments/assets/0d9099e3-17d0-4716-8f68-bd38b39ff245)

![image](https://github.com/user-attachments/assets/9979bf44-091d-4ce4-9dae-250e0fb1c2cf)
